
name: Install Python Dependencies
description: Clones app repo and installs pip dependencies

runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Clone python-greetings repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: greetings

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
      working-directory: greetings
