name: Install Python Dependencies
description: install pip 
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies with pip
      run: pip install -r requirements.txt
      shell: powershell
