
name: Deploy App
description: Clones and starts app with pm2

inputs:
  env_name:
    required: true
  port:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Clone python-greetings repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: greetings

    - name: Stop existing app
      run: pm2 delete greetings-app-${{ inputs.env_name }} || exit 0
      shell: bash

    - name: Start app with pm2
      run: pm2 start app.py --name greetings-app-${{ inputs.env_name }} -- --port ${{ inputs.port }}
      shell: bash
      working-directory: greetings
