name: Greetings Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-on-dev:
    name: Deploy and Test on Dev
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run deploy and test action
        uses: ./.github/actions/test
        with:
          env_name: dev
          port: 5000
